### ISSUE TITLE
关于退出多屏后歌词定位异常的问题

### ISSUE THREAD

**Issue by TheFunny** [cnbluefire/HotLyric#1]
笔记本使用外接显示器作为主屏幕，歌词放在外接显示器上。拔出外接显示器后，歌词无法正确定位到笔记本屏幕上。只有通过重置应用来初始化歌词位置。
系统是 Windows11 22000.556，当时的热词版本为1.0.48（大概），使用 LyricsEase，现在手上没有显示器无法复现。
笔记本屏幕分辨率是1920x1080，外接显示器是2560x1440，扩展模式是把外接显示器并排放置在笔记本屏幕的右侧。

**Comment by cnbluefire** [comment]
下个版本修复。
当显示器变化时，如果窗口不处于当前任何一个显示器上，则重置窗口位置。
同时设置中也添加了重置窗口位置的按钮。
