### ISSUE TITLE
手写笔无法点击歌词控件

### ISSUE THREAD

**Issue by excited233** [cnbluefire/HotLyric#12]
焦点会移至歌词窗口下层应用
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.1
体验	Windows Feature Experience Pack 1000.22632.1000.0

**Comment by cnbluefire** [comment]
最新版本可能有缓解，但是因为wpf对笔和触摸支持比较差，有些时候还是会有无法点击的情况
