### ISSUE TITLE
大佬，能否适配一下yesplayer这款播放器呢

### ISSUE THREAD

**Issue by wsxyjy** [cnbluefire/HotLyric#13]

**Comment by SpaceThing** [comment]
希望适配+1

**Comment by cnbluefire** [comment]
yesplayer看起来并没有接入SMTC的进度，所以暂时不会适配

**Comment by cnbluefire** [comment]
对YesPlayerMusic做了一些适配，检查下更新看看

**Comment by wsxyjy** [comment]
> 对YesPlayerMusic做了一些适配，检查下更新看看

感谢大佬，非常好用

**Comment by tylvn** [comment]
> 对YesPlayerMusic做了一些适配，检查下更新看看

如何在 YesPlayMusic 中打开热词呢？

**Comment by cnbluefire** [comment]
> > 对YesPlayerMusic做了一些适配，检查下更新看看
> 
> 如何在 YesPlayMusic 中打开热词呢？

不支持，需要手动打开热词

**Comment by tylvn** [comment]
> > > 对YesPlayerMusic做了一些适配，检查下更新看看
> > 
> > 
> > 如何在 YesPlayMusic 中打开热词呢？
> 
> 不支持，需要手动打开热词

手动打开热词后没有任何反应。
