### ISSUE TITLE
能不能增加一个WebSocket通信方式的接口（类似 WebNowPlaying接口）

### ISSUE THREAD

**Issue by huhuime** [cnbluefire/HotLyric#14]
能不能增加一个WebSocket通信方式的接口（类似 [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying)接口，可能需要在加一个歌词传递的接口）这样网页上只要写个适配脚本就能接入或者某些软件也能注入js方式强行接入（比如：[n](https://github.com/huhuime/WebNowPlayingCloudMusicBridge)）
![image](https://user-images.githubusercontent.com/6631239/173482868-c81d3bb9-9cdc-4fb2-9242-433eca2eba38.png)

**Comment by cnbluefire** [comment]
WebNowPlaying的实现方式是C#端开启WebSocket服务器，网页连接，如果热词直接接入WenNowPlaying的话，会和WenNowPlaying的C#端互斥，如果完全重新做一套维护成本太高了。
所以目前不考虑这个方案。
