### ISSUE TITLE
有关适配问题

### ISSUE THREAD

**Issue by subframe7536** [cnbluefire/HotLyric#15]
请问实现适配yesplaymusic是通过读取navigator.mediasession获取metadata实现的吗？这样的话是否可以做到适配其他基于electron的播放器？或者开放一个公共的接口让开发者自行适配？
- 初学萌新一枚，想自己用elecrton写个本地播放器，感觉这个可以直接用，不需要重复造轮子了2333

**Comment by cnbluefire** [comment]
yesplayermusic向smtc提供了正在播放的媒体信息，但是未提供播放进度。
播放进度使用了yesplayermusic提供的http api获取。[见此处](https://github.com/qier222/YesPlayMusic/issues/616#issuecomment-827771888)
hyplayer、lyricease、spotify都向smtc提供了播放进度信息，推荐使用这种方法集成。

**Comment by subframe7536** [comment]
感谢回复~
