### ISSUE TITLE
能支持桌面版的音乐播放器吗？

### ISSUE THREAD

**Issue by inkss** [cnbluefire/HotLyric#24]
样式很好看，能支持桌面版QQ音乐等的歌词显示吗？

另，添加一个竖排显示？

![Program Manager_22-07-24_13-37-02](https://user-images.githubusercontent.com/31947043/180633803-4a2c9750-9e35-4d36-b829-3e20f3149676.png)

**Comment by cnbluefire** [comment]
QQ音乐桌面版是带了桌面歌词的，热词目前只给没有桌面歌词的软件提供支持
