### ISSUE TITLE
窗口无法保存在副屏

### ISSUE THREAD

**Issue by wldll** [cnbluefire/HotLyric#30]
我想把歌词窗口放在监控屏。但是歌词窗口无法锁定在对角分离放置（鼠标无法到达）的副屏。把副屏挪开窗口就弹回主屏了。

**Comment by cnbluefire** [comment]
因为之前有人反馈拔掉屏幕热词窗口就不见了，相比来说这个需求比较少
你可以试试在热词设置中关闭“屏幕设置变动时自动重置窗口位置”选项，应该有缓解

**Comment by wldll** [comment]
谢谢！不过效果不太好，关闭“屏幕设置变动时自动重置窗口位置”选项后，窗口会丢失Orz
