### ISSUE TITLE
能增加窗口置顶的选项吗？

### ISSUE THREAD

**Issue by season8** [cnbluefire/HotLyric#34]
主要是想实现伪任务栏歌词，但热词有时候会跑到任务栏下方，被半透明任务栏遮住了，要是能强制置顶就好了😀

ps: 把热词放到任务栏上方，再配合TranslucentTB使任务栏透明或者半透明，效果真的超级棒

**Comment by cnbluefire** [comment]
始终高于任务栏在技术上是可以实现的，需要hook explorer，稳定性会降低，所以现在没有做
