### ISSUE TITLE
请求更换新的置顶方案实现

### ISSUE THREAD

**Issue by huoyan1231** [cnbluefire/HotLyric#37]
目前的实现根本无法置顶,请求更换新的实现

**Comment by cnbluefire** [comment]
可以具体描述一下什么情况下无法置顶吗

**Comment by huoyan1231** [comment]
> 
基本和 #16 相同
实际表现为在任何情况下均无法置顶
在点击任务栏后可以正常显示,此时切换任意应用到前台均会遮挡程序

**Comment by cnbluefire** [comment]
本地无法复现

**Comment by huoyan1231** [comment]
https://user-images.githubusercontent.com/53113734/208415471-89e51c00-86e6-4ab7-8c2f-01799605b090.mp4

**Comment by cnbluefire** [comment]
抽空再说吧 我冠上了

**Comment by huoyan1231** [comment]
问题已解决，是crosshair X程序导致的
