### ISSUE TITLE
给个有关显示的建议

### ISSUE THREAD

**Issue by minecraftfen** [cnbluefire/HotLyric#39]
可以添加一个通过检查屏幕色彩亮度自动切换字体颜色的功能吗
或者可以试试用字体阴影代替字体描边来确保在暗色和亮色背景下都能看清，这样更美观一些。
例如白字+黑阴影，黑字+白阴影的组合

**Comment by minecraftfen** [comment]
我写了个示例
[在这里](https://codepen.io/0hacker/pen/PoBwKOQ)
这是预览图片
![预览图片](https://user-images.githubusercontent.com/42016099/208842442-9182d570-c8a1-46cb-98c8-88da0bb856e3.png)

**Comment by cnbluefire** [comment]
wpf的阴影非常吃性能，不太想加

**Comment by balthild** [comment]
可以做一个开关，让不在意性能的人自己打开吧？
