### ISSUE TITLE
clash系统代理bug

### ISSUE THREAD

**Issue by limbia** [cnbluefire/HotLyric#45]
歌词没反应,老哥啥时候有空用用clash试试修下呗233

**Comment by Big-Cake-jpg** [comment]
> 歌词没反应,老哥啥时候有空用用clash试试修下呗233

Windows 默认阻止商店应用向本地网络发送数据包，请尝试使用 Clash for Windows 内的“UWP Loopback”选项或者商店内的“网络回环管理器”为热词启用网络回环。

![image](https://user-images.githubusercontent.com/76810494/216483769-9fcfdf55-d07c-47de-bf29-77f5fe007abc.png)
![image](https://user-images.githubusercontent.com/76810494/216483820-c10360c6-f9cd-49f9-9689-508e07545fa6.png)

**Comment by limbia** [comment]
> > 歌词没反应,老哥啥时候有空用用clash试试修下呗233
> 
> Windows 默认阻止商店应用向本地网络发送数据包，请尝试使用 Clash for Windows 内的“UWP Loopback”选项或者商店内的“网络回环管理器”为热词启用网络回环。
> 
> ![image](https://user-images.githubusercontent.com/76810494/216483769-9fcfdf55-d07c-47de-bf29-77f5fe007abc.png) ![image](https://user-images.githubusercontent.com/76810494/216483820-c10360c6-f9cd-49f9-9689-508e07545fa6.png)

用了回环还是这样。。

**Comment by Nitmi** [comment]
> 

我也遇到了同样的问题，拜托求解。

**Comment by cnbluefire** [comment]
楼上遇到问题的朋友们，麻烦加一下QQ群 1145646224 联系管理员里的热词开发（就是我），帮忙测试一下
