### ISSUE TITLE
【功能请求】使用共享的 Windows App 运行时

### ISSUE THREAD

**Issue by FrzMtrsprt** [cnbluefire/HotLyric#47]
删去应用中自带的 Windows App 运行时，改用由微软商店自动部署的共享运行时，可以减小一半以上的应用体积，节省存储空间。

**Comment by cnbluefire** [comment]
Windows商店并不存在共享的dotnet runtime

**Comment by FrzMtrsprt** [comment]
不太了解 WinUI 开发，但 [这个项目](https://github.com/Gaoyifei1011/GetStoreApp) 使用了共享的 Windows App 运行时，主包只有 65MB 大小，可以手动脚本安装依赖，也可以通过包安装器自动安装依赖。不知道热词是否也能采用这种方法？

**Comment by cnbluefire** [comment]
可热词不是winui3开发的，也根本没用到wasdk啊

**Comment by FrzMtrsprt** [comment]
明白了

**Comment by cnbluefire** [comment]
他的项目体积小应该是因为开了PublishTrimmed，热词是用wpf开发的，官方文档的描述如下

> Windows Presentation Foundation (WPF) 框架大量利用反射，而某些功能则很大程度上依赖于运行时代码检查。 在 .NET 6 中，剪裁分析无法保留 WPF 应用程序的所有必需代码。 遗憾的是，在剪裁后几乎没有 WPF 应用可运行，因此 .NET 6 SDK 中已禁用对 WPF 的剪裁支持。

**Comment by FrzMtrsprt** [comment]
重写后是否考虑对发布体积进行优化呢

**Comment by cnbluefire** [comment]
暂时不考虑，trim还存在很多问题，会增加开发难度。
通过微软商店分发app的时候，会自动启用增量更新，所以app体积不是问题。

**Comment by FrzMtrsprt** [comment]
好的，明白了
