### ISSUE TITLE
全屏隐藏失败

### ISSUE THREAD

**Issue by hanxuyuan** [cnbluefire/HotLyric#5]
打开设置中“出现全屏窗口时隐藏”功能，本机实测失败。

另外可否增加一个功能，暂停放歌的时候，歌词自动隐藏呢？

PS：Windows10 LTSC，64bit，LyricEase播放器

**Comment by hanxuyuan** [comment]
另外再增加取消固定前置功能？貌似它一打开就是固定前置，不能被别的软件界面覆盖后置。

**Comment by cnbluefire** [comment]
全屏隐藏功能使用通知api获取状态，如果全屏的app没有设置通知状态，热词也获取不到。如果判断前台窗口是否全屏资源占用比较大，不考虑此方案。

**Comment by cnbluefire** [comment]
暂时不会添加取消置顶的功能，暂停自动隐藏未来版本会提供。

**Comment by cnbluefire** [comment]
已提交暂停时自动隐藏功能
