### ISSUE TITLE
增加歌词描边样式

### ISSUE THREAD

**Issue by StringNu11** [cnbluefire/HotLyric#54]
在5月3号使用winui3更新那次后，歌词描边的边框变成了类似向内描边的样式，看起来字体变得很窄，即使拖拽热词窗口改变字号也达不到更新之前的样子，我更喜欢之前那种描边边框在外面的样式。能否增加一个复选框来设置这个效果

**Comment by JimHans** [comment]
同求，现在的描边很不习惯，而且在白色背景下新增的阴影效果的文字对比度也达不到之前的效果

**Comment by cnbluefire** [comment]
> 同求，现在的描边很不习惯，而且在白色背景下就算打开新增的阴影效果，文字对比度也达不到之前那么高，看着很费劲。

在小字号时描边质量非常差，现在会根据字号大小自动移除描边。如果需要一直显示可以在设置中调整描边选项的设置。

**Comment by JimHans** [comment]
> > 同求，现在的描边很不习惯，而且在白色背景下就算打开新增的阴影效果，文字对比度也达不到之前那么高，看着很费劲。
> 
> 在小字号时描边质量非常差，现在会根据字号大小自动移除描边。如果需要一直显示可以在设置中调整描边选项的设置。

就是，请问下能不能回到之前旧版本的描边方式呢？新版确实开了自动后小字号不会描边了，但是旧版本同样字号下效果其实不错 ，而新版就会让字非常细了。

**Comment by cnbluefire** [comment]
> > > 同求，现在的描边很不习惯，而且在白色背景下就算打开新增的阴影效果，文字对比度也达不到之前那么高，看着很费劲。
> > 
> > 
> > 在小字号时描边质量非常差，现在会根据字号大小自动移除描边。如果需要一直显示可以在设置中调整描边选项的设置。
> 
> 就是，请问下能不能回到之前旧版本的描边方式呢？新版确实开了自动后小字号不会描边了，但是旧版本同样字号下效果其实不错 ，而新版就会让字非常细了。

之前的方式有一些潜在的问题，肯定不会使用之前的方式了

**Comment by JimHans** [comment]
> > > > 同求，现在的描边很不习惯，而且在白色背景下就算打开新增的阴影效果，文字对比度也达不到之前那么高，看着很费劲。
> > > 
> > > 
> > > 在小字号时描边质量非常差，现在会根据字号大小自动移除描边。如果需要一直显示可以在设置中调整描边选项的设置。
> > 
> > 
> > 就是，请问下能不能回到之前旧版本的描边方式呢？新版确实开了自动后小字号不会描边了，但是旧版本同样字号下效果其实不错 ，而新版就会让字非常细了。
> 
> 之前的方式有一些潜在的问题，肯定不会使用之前的方式了

好吧，那就理解了，阴影也行
