### ISSUE TITLE
背景之外多了一层白色背景

### ISSUE THREAD

**Issue by Yasukii22** [cnbluefire/HotLyric#55]
![Snipaste_2023-05-18_22-00-14](https://github.com/cnbluefire/HotLyric/assets/79858014/666a85b2-4320-4e6d-9a00-89ea5fd0cd6b)
如图

**Comment by Leinbow** [comment]
我也遇到了，系统是win10 22h2

**Comment by cnbluefire** [comment]
更新1.3.10试试

**Comment by Yasukii22** [comment]
好的解决了 谢谢（昨晚怎么重装都还是那样）
