### ISSUE TITLE
Spotify 不支持 Microsoft Store 版本

### ISSUE THREAD

**Issue by Lutra-Fs** [cnbluefire/HotLyric#6]
## 问题
使用 [Microsoft Store](https://www.microsoft.com/store/p/spotify-music/9ncbcszsjrsb?cid=spotifyweb-windows10-store-direct) 版本的 Spotify 时 无论打开或关闭 桌面重叠 热词都不能识别。 更换为官网版可以正常使用
## Expect behavior
可以使用 Microsoft Store 版本的 Spotify
### Note:
使用Spotify账户登录以获取当前用户的活动不知是否可

**Comment by cnbluefire** [comment]
已添加商店版spotify支持，请等待商店审核。
另外，不会与spotify做过多集成。
