### ISSUE TITLE
Feature Request: Win平板的屏幕旋转适配

### ISSUE THREAD

**Issue by minecraftfen** [cnbluefire/HotLyric#64]
问题：运行于平板设备的Windows 11原生支持基于设备陀螺仪数据自动旋转屏幕方向，但在触发旋转后可能导致似乎基于屏幕左上角偏移值定位的歌词显示窗口位置超出屏幕范围或产生其他有关位置的非预期行为。
建议解决方案：屏幕方向变化可能不只会在平板上发生，台式机也可以调整支架旋转屏幕方向，之后手动在系统设置中更改方向。所以个人认为，为了泛用性考虑，可以对于每个屏幕每个屏幕方向单独记忆窗口位置，或者说对于每个屏幕保存四个位置。
此外也应该在旋转屏幕后检查窗口位置有效性，并在必要时进行重置。
附加：另一种解决方案是吸附，也就是用户调整位置时记忆相对于任务栏或其他系统UI元素的位置，更新屏幕方向时基于系统UI相对位置更新窗口状态。也可以在设置中直接提供一个“在任务栏上方居中”的选项。

**Comment by cnbluefire** [comment]
设置中提供了屏幕变动时重置窗口位置的选项，也可以在窗口超出屏幕范围时手动重置位置。歌词作为一个瞬态窗口设计，不考虑提供更复杂的定位功能。

**Comment by minecraftfen** [comment]
Emm，话说，如果是不打算加的话，close这个issue的时候不是应该选not planned而不是completed吗？ :joy:
