### ISSUE TITLE
能否添加一个使用Windows 强调色的歌词样式?

### ISSUE THREAD

**Issue by frg2089** [cnbluefire/HotLyric#8]
- [ ] 卡拉OK歌词文字颜色可以使用 Windows 主题的强调色
  - [ ] 根据颜色不同自动判断使用黑色或白色描边
- [ ] Windows 的强调色在被更改时歌词样式可以立即跟随变换

[Windows 应用中的颜色 - Windows apps | Microsoft Docs](https://docs.microsoft.com/windows/apps/design/style/color#accent-color)

**Comment by cnbluefire** [comment]
不考虑添加
