### ISSUE TITLE
窗口位置bug

### ISSUE THREAD

**Issue by jinqimu** [cnbluefire/HotLyric#9]
版本	Windows 11 家庭版
版本	21H2
安装日期	‎21/‎09/‎01
操作系统版本	22000.675
体验	Windows 功能体验包 1000.22000.675.0

每次重新唤起热词时（包括缩小热词再打开，以及暂停时自动隐藏），歌词界面的位置会变更为左下角

**Comment by cnbluefire** [comment]
新版本添加了“屏幕设置变动时自动重置窗口位置”选项，关掉这个选项应该能缓解这个现象

**Comment by Jason96170** [comment]
固定位置後，重新開啟程式可能也有幫助。
